PB-9637: Add changes for killing preflight
Signed-off-by: Kartik Garg <kgarg@purestorage.com>

diff --git a/charts/px-central/templates/px-backup/pre-install-hook/pre-install-check.yaml b/charts/px-central/templates/px-backup/pre-install-hook/pre-install-check.yaml
--- a/charts/px-central/templates/px-backup/pre-install-hook/pre-install-check.yaml
+++ b/charts/px-central/templates/px-backup/pre-install-hook/pre-install-check.yaml
@@ -253,11 +253,43 @@ spec:
                       - "false"
               {{- end }}
       containers:
+        - name: linkerd-shutdown
+          image: bitnami/kubectl:latest
+          command: ["/bin/sh"]
+          args:
+            - "-c"
+            - |
+              if ! command -v curl >/dev/null 2>&1; then
+                echo "curl not found, installing..."
+                if command -v apt-get >/dev/null 2>&1; then
+                  mkdir -p /var/lib/apt/lists/partial
+                  apt-get update && apt-get install -y curl
+                elif command -v apk >/dev/null 2>&1; then
+                  apk add --no-cache curl
+                else
+                  echo "Error: No known package manager found."
+                  exit 1
+                fi
+              fi
+        
+              echo "Waiting for main container to exit..."
+              while kubectl get pod "$(hostname)" -n {{ .Release.Namespace }} \
+                -o jsonpath='{.status.containerStatuses[?(@.name=="pxbackup-pre-flight-checker")].state.terminated.reason}' \
+                | grep -qv Completed; do
+                sleep 2
+              done
+        
+              echo "Main container exited. Shutting down Linkerd proxy..."
+              curl -X POST http://localhost:4191/shutdown
         - name: pxbackup-pre-flight-checker
           image: {{ printf "%s/%s/%s:%s" .Values.images.preSetupHookImage.registry .Values.images.preSetupHookImage.repo .Values.images.preSetupHookImage.imageName .Values.images.preSetupHookImage.tag }}
           imagePullPolicy: {{ .Values.images.pullPolicy }}
           command: [ "/pxcentral-hook/bin/pxcentral-hook" ]
           args: [ "--hook=preflight-check" ]
+          lifecycle:
+            preStop:
+              exec:
+                command: ["/bin/sh", "-c", "curl -X POST http://localhost:4191/shutdown"]
           env:
             - name: NAMESPACE
               value: {{ .Release.Namespace }}
